import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    componentsSidebar: [{ type: "autogenerated", dirName: "components" }],
    coreSidebar: [{ type: "autogenerated", dirName: "mad-core" }],
    navigationSidebar: [{ type: "autogenerated", dirName: "mad-navigation" }],
    toastSidebar: [{ type: "autogenerated", dirName: "mad-toast" }],
    tagOCRSidebar: [{ type: "autogenerated", dirName: "mad-tag-ocr" }],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
