name: 🐛 Bug Report
description: File a bug report
title: "[TITLE]"
labels: ["bug"]

body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!

    - type: dropdown
      id: package
      attributes:
          label: Package / App
          description: What package or app does the bug appear from?
          multiple: false
          options:
              - MAD Components
              - MAD Chronicles
              - MAD Core
              - React Native Skia Draw
              - Maintenance API typescript wrapper
              - ESLint Equinor MAD
              - MAD DFW
              - MAD Docs
              - Other
      validations:
          required: true

    - type: input
      id: version
      attributes:
          label: Version
          description: What package or app version did the bug occur in?
          placeholder: Version number
      validations:
          required: true

    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: Describe the issue here...
      validations:
          required: true

    - type: textarea
      id: other
      attributes:
          label: Other info
          description: Please provide any additional details should you have some
          placeholder: Details, context, code snippets etc...
      validations:
          required: false

    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description:
              Please copy and paste any relevant log output. This will be automatically formatted
              into code, so no need for backticks.
          render: shell
